# Generated by Django 2.1.7 on 2019-03-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190322_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='food_table',
        ),
    ]
