# Generated by Django 2.1.7 on 2019-03-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190323_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_table',
            old_name='Acct_Num',
            new_name='Carbonhydrates',
        ),
        migrations.AddField(
            model_name='food_table',
            name='Fat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_table',
            name='Fiber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_table',
            name='Name',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_table',
            name='Protein',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
