# Generated by Django 2.1.7 on 2019-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190328_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(choices=[('Lose weight', 'Lose weight'), ('Keep', 'Keep'), ('Gain Weight/Muscle', 'Gain Weight/Muscle')], default='Keep', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cur_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_cook',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.IntegerField(blank=True),
        ),
    ]
