# Generated by Django 2.1.7 on 2019-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20190328_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
