# Generated by Django 2.1.7 on 2019-03-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20190328_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedby',
            old_name='foodID',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='generatedby',
            old_name='planID',
            new_name='plan',
        ),
    ]
