# Generated by Django 2.1.7 on 2019-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190328_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(choices=[('Lose Fat', 'Lose Fat'), ('Keep', 'Keep'), ('Gain Weight/Muscle', 'Gain Weight/Muscle')], default='Keep', max_length=20),
        ),
    ]
