# Generated by Django 2.0.7 on 2019-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190328_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cur_weight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='carb',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fib',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_cook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tgt_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_cal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(choices=[('VA', 'Very Active'), ('AC', 'Active'), ('NA', ' Not Active')], default='AC', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_goal',
            field=models.CharField(choices=[('LF', 'Lose Fat'), ('GM', 'Gain Muscle'), ('TF', 'Transform')], default='TF', max_length=2),
        ),
    ]
